spring:
  application:
    name: eureka

management:
  security:
    enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
---
spring:
  profiles: single

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  profiles: peer1

server:
  port: 8761

eureka:
  instance:
    hostname: eureka-peer1  # TODO:overwrite or hack hosts file
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-peer2:8762/eureka/  # TODO:overwrite host name

---
spring:
  profiles: peer2

server:
  port: 8762

eureka:
  instance:
    hostname: eureka-peer2 # TODO:overwrite or hack hosts file
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://eureka-peer1:8761/eureka/ # TODO:overwrite host name


---
spring:
  profiles: fast-discovery

eureka:
  server:
    # 关闭自我保护
    enable-self-preservation: false
    # 清理间隔(单位毫秒,默认是60*1000)
    eviction-interval-timer-in-ms: 20000