###==========================================================================================###
## 部署
#  重要的外部参数
#  --eureka.client.service-url.defaultZone="http://192.168.0.166:8761/eureka/,http://192.168.0.166:8762/eureka/"
#
#
#  可选的外部参数
#  -Dspring.cloud.inetutils.preferredNetworks=192.168.0
#  --spring.profiles.active=fast-discovery
###==========================================================================================###

server:
  port: 18002


---
spring:
  profiles: dev

---
spring:
  profiles: test


---
spring:
  profiles: fast-discovery

eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30